[project]
name = "predict-rated-venues"
version = "0.1.0"
description = "Predição de avaliação de estabelecimentos em Toronto (F1-Score)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "en-core-web-md",
    "ipykernel>=7.3.0",
    "ipython>=9.16.1",
    "nltk",
    "numpy<2",
    "openpyxl>=3.1.5",
    "pandas",
    "scikit-learn",
    "spacy",
    "tqdm",
    "xgboost",
]

[tool.ruff]
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
# Habilitar Pyflakes (F), pycodestyle (E) e pydocstyle (D)
select = ["E", "F"]
ignore = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.uv.sources]
en-core-web-md = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.7.1/en_core_web_md-3.7.1-py3-none-any.whl" }
